name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        pip3 install -r requirements.txt
        pip3 install pytest pylint==2.4.4
    - name: test
      run: pytest
    - name: lint
      run: pylint automig
