name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '>=3.6'
    - name: deps
      run: |
        pip install -r requirements.txt
        pip install pytest pylint
        sudo apt-get install git
    - name: test
      run: pytest
    - name: lint
      run: pylint automig
