name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    - name: checkout
      run: |
        git clone https://github.com/abe-winter/automigrate.git
        cd automigrate
        git checkout $GITHUB_SHA
    - uses: actions/setup-python@v1
      with:
        python-version: '>=3.6'
    - name: deps
      working-directory: automigrate
      run: |
        pip install -r requirements.txt
        pip install pytest pylint
        sudo apt-get install git
    - name: test
      working-directory: automigrate
      run: pytest
    - name: lint
      working-directory: automigrate
      run: pylint automig
